# This is a basic workflow that is manually triggered

name: Deploy Signal Workflow

# Controls when the workflow will run
on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DeployPong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          curl -X POST https://api.github.com/PortoSpots/WebDev/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "DeployPong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
